repos:
  - repo: local
    hooks:
      - id: shellcheck
        name: shellcheck
        entry: shellcheck
        language: system
        pass_filenames: true
        types_or: [shell]
        files: ^bash/.*bash$
        args:
          - -x   # follow `source` statements (use correct relative paths)
